name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host: [HOST_POLAND, HOST_FINLAND]
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Copy build to Server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets[matrix.host] }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: target/release/simple-server
          target: /home/deploy/

      - name: Restart service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets[matrix.host] }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            chmod +x /home/deploy/target/release/simple-server
            sudo systemctl restart simple-rust-server
